file_dir:
    md: /home/rain
    mm: /home/rain
    # md:/home/rain/doc/samrain.github.com/_posts
default.mm:
    mdfname: default.md
    layout: post
    category: 学习
    tags: default
    title: default-title
    mmLink: http://samrainhan.github.com
差额选举的奥秘.mm:
    mdfname: 2012-11-19-What\s-the-Competitive-election.md
    layout: post
    category: manage
    tags: 选举,评优,评选
    title: 什么是差额选举？
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeINjVkb1lFajZXWVk
Markdown语法.mm:
    mdfname: 2012-11-22-Markdown-Grammar.md
    layout: post
    category: tech
    tags: 轻,github,博客,markdown,平板文件
    title: Markdown语法
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIMmhPN3Bvc0ZlZG8
Sublime Text2.mm:
    mdfname: 2012-11-22-Sublime-Text2.md
    layout: post
    category: tech
    tags: 轻,文本编辑器,ide
    title: Sublime Text2简介
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIN1ZzSTg5TmQyVzA
Github简单使用.mm:
    mdfname: 2012-11-27-Simple-to-use-Github.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,项目博客,产品博客
    title: Github简单使用
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeILXhqWG1tZmVYT28
双软认证.mm:
    mdfname: 2012-11-28-The-identification-software-companies-and-software-product-registration.md
    layout: post
    category: company
    tags: 资质认证,企业优惠,减免税,双软认证,双软认定
    title: what are 双软认证
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRGQ2NTJkQng5a1U
程序员的阅读清单.mm:
    mdfname: 2012-11-30-Programmer-reading-list.md
    layout: post
    category: tech
    tags: 程序员阅读,阅读清单,教科书,课外读物
    title: 程序员的阅读清单
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdkY2RVdSLWtLc0U
通过Github建博客.mm:
    mdfname: 2012-12-10-Built-blog-by-github.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,建博客
    title: 通过Github建博客
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRVczRmZtRV85RFk
用Freemind写博客.mm:
    mdfname: 2012-12-10-write-blog-by-freemind.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,建博客
    title: 用Freemind写博客
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdXZ1enJYbUNEV2M
实习生课程表.mm:
    mdfname: 2012-12-16-intern-curriculum.md
    layout: post
    category: manage
    tags: 实习生,课程,实习生课程
    title: 实习生课程表
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIZzduOURwampJaHM
旅游风景区清单.mm:
    mdfname: 2012-12-28-list-of-tourism-scenic-area.md
    layout: post
    category: family
    tags: 旅游,风景区,旅行
    title: 旅游风景区清单
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeISDFnbTVFZjgwSTQ
2013元旦温泉游.mm:
    mdfname: 2012-12-28-2013-new-year-day-spa-tour.md
    layout: post
    category: family
    tags: 2013元旦,温泉,黄山,歙县,旅行
    title: 2013元旦温泉游
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRlk2YTNEZ08zaWc
江浙温泉大全.mm:
    mdfname: 2012-12-28-2013-Jiangsu-and-zhejiang-spa-daquan.md
    layout: post
    category: family
    tags: 温泉,江苏,浙江,上海,旅行
    title: 江浙温泉大全
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdnVkcjdTOXQxMlU
如何把VIM变成Python IDE.mm:
    mdfname: 2012-08-16-how-to-become-VIM-python-IDE.md
    layout: post
    category: tech
    tags: VIM,python,IDE
    title: 如何把VIM变成Python IDE
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIaFMzZnJ4UWgwdEU
旅游-清迈-攻略.mm:
    mdfname: 2013-01-15-Chiang-Mai-travel-Raiders.md
    layout: post
    category: family
    tags: 旅游,清迈,攻略
    title: 清迈旅游攻略
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIUUxMWWxNVTltMHM/edit
Git命令释义.mm:
    mdfname: 2013-01-15-Git-command-Interpretation.md
    layout: post
    category: tech
    tags: Git,Git命令
    title: Git命令释义
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIRGFfRGdlYkJOU0k/edit
使用VPN-命令行CLI方式-ubuntu.mm:
    mdfname: 2013-01-15-use-VPN-by-CLI-command-on-Ubuntu.md
    layout: post
    category: tech
    tags: VPN,Ubuntu,CLI
    title: 在Ubuntu上使用命令行CLI方式使用VPN
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIbWRnWDNwT0NtcG8/edit
Install Gentoo In Virtualbox.mm:
    mdfname: 2013-01-15-Install-Gentoo-In-Virtualbox.md
    layout: post
    category: tech
    tags: Gentoo,Virtualbox,虚拟机,linux
    title: Install Gentoo In Virtualbox
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIT2t2cDlpMWI3anM/edit
解密磁盘碎片.mm:
    mdfname: 2013-01-15-Disk-fragmentation.md
    layout: post
    category: tech
    tags: fragmentation,disk,linux,磁盘碎片
    title: 解密磁盘碎片
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIN0otdUZvc2g0OTA/edit
Chrome介绍.mm:
    mdfname: 2013-03-11-Chrome.md
    layout: post
    category: tech
    tags: chrome,browser,google,chromium
    title: Chrome介绍
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIWk1TNXZOdkpMUGs/edit
GOOGLE搜索从入门到精通.mm:
    mdfname: 2013-03-11-google-search-tips.md
    layout: post
    category: tech
    tags: google,search,tips
    title: GOOGLE搜索从入门到精通
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIdFIzcENLWDJVTG8/edit?usp=sharing
小儿常用药.mm:
    mdfname: 2013-03-11-commonly-used-drugs-in-children.md
    layout: post
    category: family
    tags: drugs,children,medicine,sickness,fault
    title: 小儿常用药
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIUFVsY09QalI2aU0/edit?usp=sharing
VI学习.mm:
    mdfname: 2013-03-11-study-VI.md
    layout: post
    category: tech
    tags: VI,VIM
    title: 学习VI
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIODc4ZDhJQmI4Ym8/edit?usp=sharing
PPT模板和素材.mm:
    mdfname: 2013-03-18-PPT-templates-and-clip.md
    layout: post
    category: study
    tags: PPT,template,clip,presentation
    title: PPT模板和素材
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeINVgyeFpjN2N4ODA/edit?usp=sharing
Gmail快捷键.mm:
    mdfname: 2013-03-18-Gmail-shortcuts.md
    layout: post
    category: tech
    tags: Gmail,shortcuts,google
    title: Gmail快捷键
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeINWk1ZzZYWXZ2dE0/edit?usp=sharing
个人知识管理平台.mm:
    mdfname: 2013-03-21-personal-knowledge-management-platform.md
    layout: post
    category: study
    tags: knowledge,manage,personal
    title: 个人知识管理平台
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIaDl3YW1BYnhPMjA/edit?usp=sharing
我的工具.mm:
    mdfname: 2013-03-21-my-tools.md
    layout: post
    category: tech
    tags: 工具,tool
    title: 我的工具
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIbkJ1NmwycE90WUk/edit?usp=sharing
ITIL.mm:
    mdfname: 2013-03-25-learn-ITIL.md
    layout: post
    category: tech
    tags: ITIL,learn
    title: ITIL
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIeXZOQkp0OXBjMzA/edit?usp=sharing
LearnPython.mm:
    mdfname: 2013-03-25-learn-python.md
    layout: post
    category: tech
    tags: python
    title: LearnPython
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIcXFBNUpOdm5zaU0/edit?usp=sharing
MeetingMinutes.mm:
    mdfname: 2013-03-25-template-of-meeting-minutes.md
    layout: post
    category: tech
    tags: meeting minutes,template
    title: 会议纪要模版
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIc004MC1iWUFHRDA/edit?usp=sharing
OPENERP.mm:
    mdfname: 2013-03-25-learn-OPENERP.md
    layout: post
    category: tech
    tags: OPENERP,ERP,python
    title: OPENERP Step by Step
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIU2czNzAwQXp0YVk/edit?usp=sharing
Redmine.mm:
    mdfname: 2013-03-25-learn-redmine.md
    layout: post
    category: tech
    tags: Redmine,issue management system,bug management system
    title: learn Redmine
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIQWd5X0wwVGxKSlk/edit?usp=sharing
Ubuntu@Termintor.mm:
    mdfname: 2013-03-25-How-to-set-the-Terminator-copy-and-paste-shortcuts.md
    layout: post
    category: tech
    tags: ubuntu,Termintor,shortcuts,copy,paste
    title: 怎么设置Terminator中的复制和粘帖快捷键
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIenhmbGo4aHVCbDg/edit?usp=sharing
家庭教育.mm:
    mdfname: 2013-03-25-discuss-of-family-education.md
    layout: post
    category: tech
    tags: 家庭,家庭教育,教育
    title: 讨论家庭教育
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIaWFreGxEOHEtZUE/edit?usp=sharing
企业文化摘录.mm:
    mdfname: 2013-03-25-excerpts-of-corporate-culture.md
    layout: post
    category: tech
    tags: 企业文化,文化,企业
    title: 企业文化摘录
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIcmVGcU5ScjEtbkk/edit?usp=sharing
购买全幅相机建议.mm:
    mdfname: 2013-03-25-purchase-full-size-camera-proposals.md
    layout: post
    category: tech
    tags: 购买,全幅相机,相机
    title: 购买全幅相机建议
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIQkJRSm5IM2h3c3c/edit?usp=sharing
组织技术社区会议-泉盛.mm:
    mdfname: 2013-03-25-how-to-organize-the-technical-community-meeting.md
    layout: post
    category: manage
    tags: 组织,技术社区,社区会议,技术社区会议,组织会议
    title: 如何组织技术社区会议
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIWW55M1VvYkxyams/edit?usp=sharing
对于微信产品的一点思考(总结别人文章的).mm:
    mdfname: 2013-03-26-think-of-wechat-about-product.md
    layout: post
    category: tech
    tags: 微信,产品
    title: 对于微信产品的一点思考(总结别人文章的)
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIcVRVYVFfNHI5VUU/edit?usp=sharing
降低运营成本几点考虑.mm:
    mdfname: 2013-03-27-reduce-operating-costs.md
    layout: post
    category: manage
    tags: 降低,运营,成本
    title: 降低运营成本几点考虑
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIeU5VVVo5YllJbnM/edit?usp=sharing
周例会流程最佳实践.mm:
    mdfname: 2013-03-28-weekly-meeting-process-best-practices.md
    layout: post
    category: manage
    tags: 周例会,流程,最佳实践,周会
    title: 周例会流程最佳实践
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIbFV6U3NBcndTWkE/edit?usp=sharing
例会制度.mm:
    mdfname: 2013-03-28-system-of-regular-meeting.md
    layout: post
    category: manage
    tags: 例会,会议,制度
    title: 例会制度
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIeGNJWkNIbG9UUVU/edit?usp=sharing
新生婴儿报户口.mm:
    mdfname: 2013-03-29-household-registration-of-newborn-babies.md
    layout: post
    category: family
    tags: 婴儿,户口,登记
    title: 新生婴儿报户口
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIQlJBSTdySXpoMjQ/edit?usp=sharing
怎么填计算机软件著作权登记申请表.mm:
    mdfname: 2013-04-01-how-to-fill-the-computer-software-copyright-registration-application-form.md
    layout: post
    category: tech
    tags: 计算机,软件,著作权,登记,申请表
    title: 怎么填计算机软件著作权登记申请表
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIQlpod3N4RUNSekk/edit?usp=sharing
培训的基本规范及技巧.mm:
    mdfname: 2013-04-01-basic-norms-and-skills-of-training.md
    layout: post
    category: tech
    tags: 培训,技巧,规范
    title: 培训的基本规范及技巧
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIYXpfcFFrdHlqS1E/edit?usp=sharing
会议通用描述.mm:
    mdfname: 2013-04-02-meeting-wiki.md
    layout: post
    category: manage
    tags: 会议
    title: 会议通用描述
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIcmRBcTFCRFBkU0k/edit?usp=sharing
内部培训制度.mm:
    mdfname: 2013-04-02-internal-training-system.md
    layout: post
    category: manage
    tags: 培训
    title: 内部培训制度
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIVG8zeVQtanZ0Ykk/edit?usp=sharing
软件开发文档命名规范.mm:
    mdfname: 2013-04-02-software-development-document-naming-conventions.md
    layout: post
    category: tech
    tags: 软件开发,文档,命名,规范
    title: 软件开发文档命名规范
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIUWJkd1RidGFsR0E/edit?usp=sharing
岗位职责-信息技术部.mm:
    mdfname: 2013-04-07-responsibilities-of-the-ministry-of-information-technology.md
    layout: post
    category: manage
    tags: 信息技术部,岗位,职责
    title: 信息技术部 岗位职责
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIUEF3LUtGQ3huUG8/edit?usp=sharing
CIO工作内容.mm:
    mdfname: 2013-04-08-CIO-work.md
    layout: post
    category: manage
    tags: CIO,工作内容,工作,内容,管理
    title: CIO工作内容片段
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIaGVvdkUyOUNBQms/edit?usp=sharing
公正、平等、共享.mm:
    mdfname: 2013-04-10-fair-equality-share.md
    layout: post
    category: manage
    tags: 公正,平等,共享
    title: 公正、平等、共享
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIMnFyUzFCWjZqOXc/edit?usp=sharing
信息技术中心职责.mm:
    mdfname: 2013-04-10-the-duties-of-the-information-technology-center.md
    layout: post
    category: manage
    tags: 信息技术,职责,信息技术中心,职责信息技术中心职责
    title: 信息技术中心职责
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIdWVrQU81RjBldjg/edit?usp=sharing
看板.mm:
    mdfname: 2013-04-12-kanban.md
    layout: post
    category: manage
    tags: 看板,敏捷,软件工程
    title: 看板的一些总结
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIQjVpbEVKeUlPYlk/edit?usp=sharing
培训的一般流程.mm:
    mdfname: 2013-04-12-training-process.md
    layout: post
    category: manage
    tags: 培训,流程,培训流程
    title: 培训的一般流程
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIRVYzOUhWZGF6ZFk/edit?usp=sharing
上线前准备.mm:
    mdfname: 2013-04-23-prepare-for-go-live.md
    layout: post
    category: tech
    tags: 上线,准备
    title: 上线前准备
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeISmFFR0Y0d3NvNG8/edit?usp=sharing
企业文化墙.mm:
    mdfname: 2013-04-23-enterprise-culture-wall.md
    layout: post
    category: tech
    tags: 企业文化,文化墙
    title: 企业文化墙
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIa0M4aXZjUVRMUW8/edit?usp=sharing
吴式团队.mm:
    mdfname: 2013-04-23-wu-style-team.md
    layout: post
    category: manage
    tags: 团队
    title: 吴式团队
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIcFBMSTlHZlpkWEE/edit?usp=sharing
短句.mm:
    mdfname: 2013-04-23-short-sentences.md
    layout: post
    category: manage
    tags: 团队
    title: 名句摘录（转）
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIRWMyNGNtY3pUdlU/edit?usp=sharing
我是怎么用Evernote.mm:
    mdfname: 2013-04-23-use-evernote.md
    layout: post
    category: manage
    tags: evernote,个人知识管理
    title: 我是怎么使用evernote
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIWmVZOG14el9lQms/edit?usp=sharing
上海活动场所.mm:
    mdfname: 2013-04-23-shanghai-venues.md
    layout: post
    category: manage
    tags: 上海活动场所,活动场所,上海活动,场所
    title: 上海活动场所
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIeEpYRXYwLVRyNFE/edit?usp=sharing
《奇特的一生》.mm:
    mdfname: 2013-05-28-strange-life.md
    layout: post
    category: study
    tags: 时间管理
    title: 《奇特的一生》读书笔记
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIT0x4c3I4anZxd1E/edit?usp=sharing
Chrome很酷功能.mm:
    mdfname: 2013-05-06-chrome-cool-features.md
    layout: post
    category: study
    tags: Chrome,功能,酷
    title: Chrome很酷功能
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIR1BPX0VlYTFudWM/edit?usp=sharing
impress.js.mm:
    mdfname: 2013-05-20-impress-js.md
    layout: post
    category: study
    tags: ppt工具,酷
    title: 怎么使用impress.js
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIY3E3dDlmWDViM2s/edit?usp=sharing
linux下中文OCR.mm:
    mdfname: 2013-05-07-OCR-in-linux.md
    layout: post
    category: study
    tags: linux,OCR,中文OCR
    title: linux下中文OCR
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIMzg3c2ZfM1RPNFk/edit?usp=sharing
MapReduce.mm:
    mdfname: 2013-05-15-MapReduce.md
    layout: post
    category: study
    tags: MapReduce,数据挖掘,大数据处理
    title: MapReduce简介
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIMW9EbVhoY0owTFk/edit?usp=sharing
PPT工具.mm:
    mdfname: 2013-05-09-non-office-tools-to-make-PPT.md
    layout: post
    category: study
    tags: ppt,工具,非office
    title: 制作ppt的非office工具
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIV1Q3OFJ2MUxoNzg/edit?usp=sharing
怎么用Google日历.mm:
    mdfname: 2013-05-08-How-to-use-Google-Calendar.md
    layout: post
    category: study
    tags: Google日历,Google,日历
    title: 怎么用Google日历
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIaWFWVDhqX3RRdjQ/edit?usp=sharing
申报高新技术企业.mm:
    mdfname: 2013-07-31-how-to-be-a-high-tech-company.md
    layout: post
    category: manage
    tags: company,high-tech
    title: 如何申报高新技术企业
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIRVhRZE81ek9VTDg/edit?usp=sharing
申报政府科技项目的价值.mm:
    mdfname: 2013-07-31-what-is-the-value-of-doing-the-government-high-tech-project.md
    layout: post
    category: manage
    tags: government,high-tech,project
    title: 申报政府科技项目的价值
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIREJZRWYwSVg1OEk/edit?usp=sharing
导入google日历.mm:
    mdfname: 2013-07-31-how-to-import-into-google-calendar.md
    layout: post
    category: study
    tags: google,google calendar,import
    title: 怎样导入google日历
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIMk9lSzd0Q0trNjA/edit?usp=sharing
学习golang.mm:
    mdfname: 2013-07-31-study-golang.md
    layout: post
    category: study
    tags: golang,go program
    title: 学习golang
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIWWhKUnVDbTJJSUE/edit?usp=sharing
ThoughtWorks(中国)程序员读书雷达.mm:
    mdfname: 2013-07-31-ThoughtWorks-(China)-programmer-reading-radar.md
    layout: post
    category: study
    tags: ThoughtWorks,programe
    title: ThoughtWorks(中国)程序员读书雷达
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIbVpLZWlEZ2kycjA/edit?usp=sharing
Emacs.mm:
    mdfname: 2013-07-31-play-Emacs.md
    layout: post
    category: study
    tags: Emacs,text editor
    title: 玩转Emacs
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIMk01bnlmVXowMms/edit?usp=sharing
Nmap初体验.mm:
    mdfname: 2013-09-03-first-experience-of-Nmap.md
    layout: post
    category: study
    tags: Nmap,黑客,工具,端口扫描,网络
    title: Nmap初体验
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIQ1g2bmk0aGh2S0U/edit?usp=sharing
网络安全工具.mm:
    mdfname: 2013-09-03-network-security-tools.md
    layout: post
    category: study
    tags: 黑客,工具,网络,安全
    title: 十大网络安全工具
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeITWxoOXU1bXpTNXc/edit?usp=sharing
耳放MDAD Mini满血复活.mm:
    mdfname: 2013-09-03-MDAD-Mini-resurrection.md
    layout: post
    category: tech
    tags: 耳放,linux,音乐,驱动,MDAD Mini
    title: 耳放MDAD Mini满血复活
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIMk01bnlmVXowMms/edit?usp=sharing
露营烧烤准备材料.mm:
    mdfname: 2013-09-05-prepare-materials-for-Camping-and-BBQ.md
    layout: post
    category: family
    tags: 露营,烧烤,帐篷
    title: 露营烧烤准备材料
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIdXhTRDlrd29xZm8/edit?usp=sharing
用Emacs编辑Markdown.mm:
    mdfname: 2013-09-10-edit-markdown-file-with-Emacs.md
    layout: post
    category: study
    tags: emacs,markdown,md,md2html
    title: 用Emacs编辑Markdown
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeITG03OXphM2R1eXc/edit?usp=sharing
快速安装我的Lubuntu.mm:
    mdfname: 2013-10-16-install-Lubuntu-faster.md
    layout: post
    category: study
    tags: linux,ubuntu,lubuntu
    title: 快速安装我的Lubuntu
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeITG03OXphM2R1eXc/edit?usp=sharing
客户营销流程最佳实践.mm:
    mdfname: 2013-12-12-customer-marketing-process-best-practices.md
    layout: post
    category: sale
    tags: 客户,营销,流程,实践,sale,process
    title: 客户营销流程最佳实践
    mmLink: https://drive.google.com/file/d/0B1DrsqrLRzeISnNNNDJWaGN4NGM/edit?usp=sharing
园区智能化方案.mm:
    mdfname: 2013-12-12-park-intelligent-solutions.md
    layout: post
    category: tech
    tags: 园区,智能化,物流,
    title: 园区智能化方案
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeITG03OXphM2R1eXc/edit?usp=sharing




